name: Build Windows EXE

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller --windowed --onefile --name PDF_RAG_STUDIO --collect-all chromadb --collect-all posthog --collect-all onnxruntime --collect-all tokenizers --hidden-import chromadb.api.rust pdf_rag_gui.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF_RAG_STUDIO
          path: dist/PDF_RAG_STUDIO.exe
