name: Build Windows EXE

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller --onefile --name PDF_RAG_LOCAL --hidden-import chromadb.telemetry.product.posthog --hidden-import chromadb.api.segment --hidden-import chromadb.segment.impl.manager.local --hidden-import chromadb.db.impl.sqlite --hidden-import chromadb.execution.executor.local pdf_rag_local.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF_RAG_LOCAL
          path: dist/PDF_RAG_LOCAL.exe
